# Generated by Django 4.1.5 on 2023-01-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_text_post_textyou"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="textyou",
            new_name="text",
        ),
    ]
